import {
  Loader2,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  List,
  ListOrdered,
  Heading2,
  Heading3,
  Quote,
  Code,
  Link,
  Undo2,
  Redo2,
  Paintbrush,
  Image as ImageIcon,
} from 'lucide-react';

export const Icons = {
  spinner: Loader2,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strike: Strikethrough,
  bulletList: List,
  orderedList: ListOrdered,
  h2: Heading2,
  h3: Heading3,
  quote: Quote,
  code: Code,
  link: Link,
  undo: Undo2,
  redo: Redo2,
  color: Paintbrush,
  image: ImageIcon,
};
